param(
  [switch]$Clean,
  [string]$Task = 'assembleHap'
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$projectRoot = Join-Path $repoRoot 'apps\harmony'
$defaultRegistry = 'https://repo.huaweicloud.com/repository/npm/'

. (Join-Path $repoRoot 'scripts\use-harmony-tools.ps1') | Out-Null

function Find-FirstExistingPath {
  param(
    [string[]]$Candidates
  )

  foreach ($candidate in $Candidates) {
    if ([string]::IsNullOrWhiteSpace($candidate)) {
      continue
    }

    if (Test-Path $candidate) {
      return (Resolve-Path $candidate).Path
    }
  }

  return $null
}

if (-not (Test-Path $projectRoot)) {
  throw "Harmony project root not found: $projectRoot"
}

$sdkRoot = Find-FirstExistingPath @(
  (Join-Path $env:HARMONY_COMMANDLINE_TOOLS 'hwsdk')
)

if (-not $sdkRoot) {
  throw 'HarmonyOS SDK root was not found. Run npm run check:harmony-env first.'
}

$openHarmonySdkRoot = Find-FirstExistingPath @(
  (Join-Path $sdkRoot 'openharmony')
)
$sdkDirForBuild = if ($openHarmonySdkRoot) { $openHarmonySdkRoot } else { $sdkRoot }

$nodeHome = Find-FirstExistingPath @(
  $env:NODE_HOME,
  (Join-Path $repoRoot '.tooling\node-v24.14.0-win-x64')
)

if (-not $nodeHome) {
  throw 'NODE_HOME was not found. The Harmony build needs a local Node runtime.'
}

if ($env:Path -notlike "*$nodeHome*") {
  $env:Path = "$nodeHome;$env:Path"
}
$env:PATH = $env:Path

$projectNpmrc = Join-Path $projectRoot '.npmrc'
if (-not (Test-Path $projectNpmrc)) {
  throw "Harmony npmrc not found: $projectNpmrc"
}

$env:NPM_CONFIG_USERCONFIG = $projectNpmrc
$env:npm_config_userconfig = $projectNpmrc
$env:NPM_CONFIG_REGISTRY = $defaultRegistry
$env:npm_config_registry = $defaultRegistry
$env:NPM_CONFIG_STRICT_SSL = 'true'
$env:npm_config_strict_ssl = 'true'

$hvigorWrapperTools = Join-Path $env:USERPROFILE '.hvigor\wrapper\tools'
$hvigorWrapperPackage = Join-Path $hvigorWrapperTools 'package.json'
$hvigorWrapperPnpmCmd = Join-Path $hvigorWrapperTools 'node_modules\.bin\pnpm.cmd'
New-Item -ItemType Directory -Force -Path $hvigorWrapperTools | Out-Null
if (-not (Test-Path $hvigorWrapperPackage)) {
  '{"dependencies":{}}' | Set-Content -Path $hvigorWrapperPackage -Encoding ASCII
}

Push-Location $hvigorWrapperTools
try {
  $pnpmReady = $false
  if (Test-Path $hvigorWrapperPnpmCmd) {
    $pnpmVersion = & cmd /c "`"$hvigorWrapperPnpmCmd`" --version" 2>$null
    if ($LASTEXITCODE -eq 0 -and "$pnpmVersion".Trim() -eq '8.15.9') {
      $pnpmReady = $true
    }
  }

  if (-not $pnpmReady) {
    $installAttempts = 0
    do {
      $installAttempts++
      & (Join-Path $nodeHome 'npm.cmd') install pnpm@8.15.9
      if ($LASTEXITCODE -eq 0) {
        $pnpmReady = $true
      } elseif ($installAttempts -lt 3) {
        Start-Sleep -Seconds 3
      }
    } while (-not $pnpmReady -and $installAttempts -lt 3)
  }

  if (-not $pnpmReady) {
    throw 'npm install pnpm@8.15.9 failed for hvigor wrapper tools after 3 attempts.'
  }

  $pnpmBinNodePath = Join-Path $hvigorWrapperTools 'node_modules\.bin\node.exe'
  $sourceNodeExePath = Join-Path $nodeHome 'node.exe'
  if (-not (Test-Path $sourceNodeExePath)) {
    throw "Node runtime executable not found: $sourceNodeExePath"
  }

  Copy-Item -Path $sourceNodeExePath -Destination $pnpmBinNodePath -Force
} finally {
  Pop-Location
}

$localPropertiesPath = Join-Path $projectRoot 'local.properties'
$localPropertiesContent = @(
  '# Generated by scripts/build-harmony.ps1',
  "hwsdk.dir=$($sdkRoot -replace '\\', '/')",
  "sdk.dir=$($sdkDirForBuild -replace '\\', '/')",
  "nodejs.dir=$($nodeHome -replace '\\', '/')",
  "npm.config.dir=$($projectRoot -replace '\\', '/')"
) -join [Environment]::NewLine

Set-Content -Path $localPropertiesPath -Value $localPropertiesContent -Encoding ASCII

$md5 = [System.Security.Cryptography.MD5]::Create()
try {
  $hashBytes = $md5.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($projectRoot))
  $projectHash = ([System.BitConverter]::ToString($hashBytes)).Replace('-', '').ToLowerInvariant()
} finally {
  $md5.Dispose()
}

$hvigorWorkspaceNodeModules = Join-Path $env:USERPROFILE ".hvigor\project_caches\$projectHash\workspace\node_modules"
if (Test-Path $hvigorWorkspaceNodeModules) {
  if ([string]::IsNullOrWhiteSpace($env:NODE_PATH)) {
    $env:NODE_PATH = $hvigorWorkspaceNodeModules
  } elseif ($env:NODE_PATH -notlike "*$hvigorWorkspaceNodeModules*") {
    $env:NODE_PATH = "$hvigorWorkspaceNodeModules;$env:NODE_PATH"
  }
}

$hvigorCliScript = Join-Path $env:USERPROFILE ".hvigor\project_caches\$projectHash\workspace\node_modules\@ohos\hvigor\bin\hvigor.js"

function Invoke-HvigorTask {
  param(
    [string]$HvigorTask
  )

  if (Test-Path $hvigorCliScript) {
    & (Join-Path $nodeHome 'node.exe') $hvigorCliScript $HvigorTask --no-daemon
  } else {
    & cmd /c ".\hvigorw.bat $HvigorTask --no-daemon"
  }

  if ($LASTEXITCODE -ne 0) {
    throw "hvigor task failed: $HvigorTask"
  }
}

Push-Location $projectRoot
try {
  & ohpm install
  if ($LASTEXITCODE -ne 0) {
    throw 'ohpm install failed in apps/harmony.'
  }

  Push-Location (Join-Path $projectRoot 'entry')
  try {
    & ohpm install
    if ($LASTEXITCODE -ne 0) {
      throw 'ohpm install failed in apps/harmony/entry.'
    }
  } finally {
    Pop-Location
  }

  if ($Clean) {
    Invoke-HvigorTask -HvigorTask 'clean'
  }

  Invoke-HvigorTask -HvigorTask $Task
} finally {
  Pop-Location
}
