$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$projectRoot = Join-Path $repoRoot 'apps\harmony'
$nodeHome = Join-Path $repoRoot '.tooling\node-v24.14.0-win-x64'

. (Join-Path $repoRoot 'scripts\use-harmony-tools.ps1') | Out-Null
$sdkRoot = Join-Path $env:HARMONY_COMMANDLINE_TOOLS 'hwsdk'

if ($env:Path -notlike "*$nodeHome*") {
  $env:Path = "$nodeHome;$env:Path"
}
$env:PATH = $env:Path

$projectNpmrc = Join-Path $projectRoot '.npmrc'
$env:NPM_CONFIG_USERCONFIG = $projectNpmrc
$env:npm_config_userconfig = $projectNpmrc
$env:NPM_CONFIG_REGISTRY = 'https://repo.huaweicloud.com/repository/npm/'
$env:npm_config_registry = 'https://repo.huaweicloud.com/repository/npm/'
$env:NPM_CONFIG_STRICT_SSL = 'true'
$env:npm_config_strict_ssl = 'true'

$hvigorWrapperTools = Join-Path $env:USERPROFILE '.hvigor\wrapper\tools'
$hvigorWrapperPnpmCmd = Join-Path $hvigorWrapperTools 'node_modules\.bin\pnpm.cmd'
New-Item -ItemType Directory -Force -Path $hvigorWrapperTools | Out-Null
if (-not (Test-Path (Join-Path $hvigorWrapperTools 'package.json'))) {
  '{"dependencies":{}}' | Set-Content -Path (Join-Path $hvigorWrapperTools 'package.json') -Encoding ASCII
}

Write-Host 'STEP A: install wrapper pnpm'
Push-Location $hvigorWrapperTools
try {
  $pnpmReady = $false
  if (Test-Path $hvigorWrapperPnpmCmd) {
    $pnpmVersion = & cmd /c "`"$hvigorWrapperPnpmCmd`" --version" 2>$null
    if ($LASTEXITCODE -eq 0 -and "$pnpmVersion".Trim() -eq '8.15.9') {
      $pnpmReady = $true
    }
  }

  if (-not $pnpmReady) {
    $attempts = 0
    do {
      $attempts++
      & (Join-Path $nodeHome 'npm.cmd') install pnpm@8.15.9 --loglevel=error
      if ($LASTEXITCODE -eq 0) {
        $pnpmReady = $true
      } elseif ($attempts -lt 3) {
        Start-Sleep -Seconds 3
      }
    } while (-not $pnpmReady -and $attempts -lt 3)
  }

  if (-not $pnpmReady) {
    throw 'npm install pnpm failed after 3 attempts.'
  }

  Copy-Item -Path (Join-Path $nodeHome 'node.exe') -Destination (Join-Path $hvigorWrapperTools 'node_modules\.bin\node.exe') -Force
} finally {
  Pop-Location
}

Write-Host 'STEP B: install ohpm (root)'
Push-Location $projectRoot
try {
  & ohpm install
  if ($LASTEXITCODE -ne 0) {
    throw 'ohpm install failed in apps/harmony.'
  }
} finally {
  Pop-Location
}

Write-Host 'STEP C: install ohpm (entry)'
Push-Location (Join-Path $projectRoot 'entry')
try {
  & ohpm install
  if ($LASTEXITCODE -ne 0) {
    throw 'ohpm install failed in apps/harmony/entry.'
  }
} finally {
  Pop-Location
}

Write-Host 'STEP D: write local.properties'
$localPropertiesPath = Join-Path $projectRoot 'local.properties'
$localPropertiesContent = @(
  '# Generated by scripts/debug-harmony-build.ps1',
  "hwsdk.dir=$($sdkRoot -replace '\\', '/')",
  "sdk.dir=$($sdkRoot -replace '\\', '/')",
  "nodejs.dir=$($nodeHome -replace '\\', '/')",
  "npm.config.dir=$($projectRoot -replace '\\', '/')"
) -join [Environment]::NewLine
Set-Content -Path $localPropertiesPath -Value $localPropertiesContent -Encoding ASCII

Write-Host 'STEP E: run hvigor assembleHap'
Push-Location $projectRoot
try {
  & cmd /c '.\hvigorw.bat assembleHap --no-daemon'
  if ($LASTEXITCODE -ne 0) {
    throw 'hvigor assembleHap failed.'
  }
} finally {
  Pop-Location
}

Write-Host 'DONE'
